[package]
name = "call_decode_output"
version = "0.1.0"
edition = "2021"

[dependencies]
hypersync-client = { path = "../../hypersync-client" }
alloy-json-abi = "1.1.0"
tokio = { version = "1", features = ["full"] }
serde_json = "1"
env_logger = "0.4"
anyhow = "1.0.89"
