[package]
name = "height_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
hypersync-client = { path = "../../hypersync-client" }
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
anyhow = "1"
