[package]
name = "hypersync-schema"
version = "0.2.3"
edition = "2021"
description = "schema utilities for hypersync"
license = "MPL-2.0"

[dependencies]
anyhow = "1"
polars-arrow = { version = "0.42", features = ["compute_cast"] }
