name: Publish to crates.io 

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      crate_name:
        description: "The crate name to publish"
        required: true
        type: choice
        options: 
        - hypersync-format
        - hypersync-schema
        - hypersync-net-types
        - hypersync-client

run-name: "Publish ${{ inputs.crate_name }} to crates.io"

jobs:
  publish_crates:
    name: Publish to crates.io 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      - name: Install Dependencies
        run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y capnproto libcapnp-dev

      - uses: actions/checkout@v2
      - name: Run publish script
        env:
          VERBOSE: true
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p ${{ inputs.crate_name }}
