name: Publish to crates.io 

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      crate_name:
        description: "The crate name to publish"
        required: true
        type: choice
        options: 
        - hypersync-format
        - hypersync-schema
        - hypersync-net-types
        - hypersync-client

jobs:
  publish_crates:
    name: Publish crates to crates.io 
    strategy:
      matrix:
        rust: [stable]
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Install Dependencies
        run: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt-get install -y capnproto libcapnp-dev

      - uses: actions/checkout@v2
      - name: Run publish script
        env:
          VERBOSE: true
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish -p ${{ inputs.crate_name }}
