[package]
name = "call_watch"
version = "0.1.0"
edition = "2021"

[dependencies]
hypersync-client = { path = "../../hypersync-client" }

tokio = { version = "1", features = ["full"] }
serde_json = "1"
ruint = "1"
env_logger = "0.4"
